# This is a basic workflow to help you get started with Actions

name: SGSI_Build

on:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'https://bigota.d.miui.com/21.5.20/miui_VANGOGH_21.5.20_44d9a365bc_11.0.zip'
  ZIP_NAME: 'test.zip'
  OS_TYPE: 'miui'
  BUILD_TYPE: 'AB'
  REPACK_NAME: 'test_action.zip'
  VERSION: '11'
  upload_WeTransfer: 'true'
  upload_action-gh-release: 'true'
  SETUP: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git wget git zip unzip curl axel
       - name: Cloning...
         run: |
             git clone https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool-12
           
       - name: Download zip...
         run: |
            cd $GITHUB_WORKSPACE/SGSI-build-tool-12
            mkdir ./tmp
            axel -n $(nproc) -U "Mozilla/5.0" $ROM_URL -o "$GITHUB_WORKSPACE/SGSI-build-tool-12/tmp/$ZIP_NAME" || wget -U "Mozilla/5.0" $ROM_URL -O "$GITHUB_WORKSPACE/SGSI-build-tool-12/tmp/$ZIP_NAME"
            echo "zip_file: $(ls "$GITHUB_WORKSPACE/SGSI-build-tool-12/tmp/")"
            
       - name: Setup Tool Utils...
         if: env.SETUP == 'true'
         run: |
            sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool-12/setup.sh
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool-12/setup.sh
            sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
            java -version
            
       - name: Building AB DEVICES SGSI...
         if: env.BUILD_TYPE == 'AB' || env.BUILD_TYPE == 'ab'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool-12/12/make.sh --AB $OS_TYPE $ZIP_NAME --fix-bug
       - name: Building A-only DEVICES SGSI...
         if: env.BUILD_TYPE == 'a-only'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --a-only $OS_TYPE $ZIP_NAME --fix-bug     
       - name: Repack output file ...
         run: |            
             cd $GITHUB_WORKSPACE/SGSI-build-tool-12
             pwd
             zip -r $REPACK_NAME ./SGSI/*
             ls "$REPACK_NAME"
       - name: Upload SGSI to WeTransfer...
         if: env.upload_WeTransfer == 'true' 
         run: |
           cd $GITHUB_WORKSPACE/SGSI-build-tool-12
           pwd
           ls "$REPACK_NAME"
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ./$REPACK_NAME
       - name: Upload SGSI to action-gh-release...
         if: env.upload_action-gh-release == 'true'
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ github.workspace }}/SGSI-build-tool-12/${{ env.REPACK_NAME }}
           name: xiaoxinSGSI-${{ env.OS_TYPE }}-${{ env.BUILD_TYPE }}-Android${{ env.VERSION }}-unpack
           tag_name: 12
           #body: Use actions auto bulid
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
